export const metadata = {
    title: 'Studio Admin - AIC CMS Portal',
    description: 'Generated by Next + Sanity',
  };
  
  export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }
  